### ISSUE TITLE
Published website is outdated

### ISSUE THREAD

**Issue by michaelarnauts** [opis/docs#15]
It seems that the published website isn't updated in quite a while.

I've noticed a typo (`regiserFile`) on this page: https://opis.io/json-schema/2.x/php-loader.html, but it has already been fixed over a year ago in https://github.com/opis/docs/commit/70da6f8827135439fef53e7f9b897c0702bffbe8

**Comment by tbreuss** [comment]
👍 I've noticed the same right now.

**Comment by sorinsarca** [comment]
Website was re-published with the latest changes
